### ISSUE TITLE
Helm Chart Usage Documentation

### ISSUE THREAD

**Issue by egulatee** [elemental-lf/benji#112]
Can you please provide some guidance on how to install benji on K8s using the helm chart?
ie:  Maybe the command used to install the chart?  

-  Does one clone this repo and point helm to it locally?  (Didn't work for me)
-  Does one use a specific helm chart repository?  (I can't seem to find one listed)

**Comment by elemental-lf** [comment]
There currently is no chart repository. The main reason being that I've been using `helmfile` to manage my `helm` usage for ages. `helmfile` supports installing charts directly from a repository:

```yaml
releases:
  - name: benji
    namespace: ceph
    chart: git::https://github.com/elemental-lf/benji.git@charts/benji-k8s?ref=v0.14.1
```
In addition installing from the directory should work as expected. Have you run `helm dependeny update` beforehand or added the `--dependency-update` flag to your `helm install` call? Could you provide the error messages that you get?

You also need to provide overrides for some values otherwise the setup won't work at all. These mainly are `benji.configuration`, `benji.crontab`, `benji.volumes` and `benji.volumeMounts`. The name of the io module instance must be the same name as the name of the RBD pool that you want to backup. In general this is `rbd`.
