### ISSUE TITLE
Human readable info on progress of backups?

### ISSUE THREAD

**Issue by bbs2web** [elemental-lf/benji#113]
So I want INFO level logging to see the progress but the output appears to be in a sort of JSON format whereas it used to only show the event itself:

We are using https://github.com/elemental-lf/benji/blob/master/scripts/ceph.sh as the '/usr/local/bin/benji-backup.sh' function script with "${BENJI_LOG_LEVEL:=INFO}"

```
[root@kvm6b ~]# . /usr/local/benji/bin/activate;
(benji) [root@kvm6b ~]# . /usr/local/bin/benji-backup.sh;
(benji) [root@kvm6b ~]# benji::backup::ceph *******************-disk0 rbd_ssd vm-132-disk-0 AutomatedBackup
Snapshot found for rbd_ssd/vm-132-disk-0 is b-2021-04-23T22:45:57.
Performing differential backup of *******************-disk0:rbd_ssd/vm-132-disk-0 from RBD snapshot b-2021-04-23T22:45:57 and Benji version *******************-disk0-6agk5p.
Removing snap: 100% complete...done.
{"event": "Starting sanity check with 0.1% of the ignored blocks.", "level": "info", "timestamp": 1619269607.4524617, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 798, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Finished sanity check. Checked 0 blocks.", "level": "info", "timestamp": 1619269607.4724786, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 831, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Starting backup of rbd:rbd_ssd/vm-132-disk-0@b-2021-04-24T15:06:44 to storage radosgw-kvm7, the newly created version is *******************-disk0-r1j2za.", "level": "info", "timestamp": 1619269607.472836, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 833, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Active transforms for storage radosgw-kvm7: zstd (zstd), aes_256_gcm (aes_256_gcm).", "level": "info", "timestamp": 1619269607.5318737, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/storage/base.py", "line": 75, "function": "__init__", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backed up 3/460 blocks (0.7%)", "level": "info", "timestamp": 1619269607.7922418, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 941, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backed up 6/460 blocks (1.3%)", "level": "info", "timestamp": 1619269607.8724086, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 941, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backed up 9/460 blocks (2.0%)", "level": "info", "timestamp": 1619269607.9244125, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 941, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
<snip>
{"event": "Backed up 459/460 blocks (99.8%)", "level": "info", "timestamp": 1619269615.0239453, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 941, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backed up 460/460 blocks (100.0%)", "level": "info", "timestamp": 1619269615.0368207, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 941, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Set status of version *******************-disk0-r1j2za to valid.", "level": "info", "timestamp": 1619269615.05754, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/database.py", "line": 466, "function": "set", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backed up metadata of version *******************-disk0-r1j2za.", "level": "info", "timestamp": 1619269615.5109656, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 1056, "function": "metadata_backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Backup successful.", "level": "info", "timestamp": 1619269615.5378041, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/benji.py", "line": 979, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
{"event": "Added label(s) to version *******************-disk0-r1j2za: AutomatedBackup=.", "level": "info", "timestamp": 1619269615.5631351, "file": "/usr/local/benji/lib/python3.7/site-packages/benji/commands.py", "line": 62, "function": "backup", "process": 4123517, "thread_name": "MainThread", "thread_id": 139809693353792}
```

If I set this as WARNING I do not get incremental information:
```
[root@kvm6b ~]# . /usr/local/benji/bin/activate;
(benji) [root@kvm6b ~]# . /usr/local/bin/benji-backup.sh;
(benji) [root@kvm6b ~]# benji::backup::ceph *******************-disk0 rbd_ssd vm-132-disk-0 AutomatedBackup
Snapshot found for rbd_ssd/vm-132-disk-0 is b-2021-04-24T15:09:26.
Performing differential backup of *******************-disk0:rbd_ssd/vm-132-disk-0 from RBD snapshot b-2021-04-24T15:09:26 and Benji version *******************-disk0-ctskkt.
Removing snap: 100% complete...done.
```

Everything else is newly reinstalled with defaults (Python virtual environment and then pip install). Herewith our configuration file:
```
(benji) [root@kvm6b ~]# cat /etc/benji.yaml
configurationVersion: '1'
logFile: /var/log/benji.log
databaseEngine: postgresql://benji-kvm6:********************************@**********************:5432/benji-kvm6
defaultStorage: radosgw-kvm6
storages:
  - name: radosgw-kvm6
    module: s3
    storageId: 1
    configuration:
      simultaneousReads: 12
      simultaneousWrites: 12
      activeTransforms:
        - zstd
        - aes_256_gcm
      awsAccessKeyId: '********************'
      awsSecretAccessKey: '****************************************'
      bucketName: benji-kvm6
      endpointUrl: https://*****************:7480/
ios:
  - name: file
    module: file
  - name: rbd
    module: rbdaio
    configuration:
      simultaneousReads: 12
      simultaneousWrites: 12
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
        - RBD_FEATURE_LAYERING
        - RBD_FEATURE_EXCLUSIVE_LOCK
        - RBD_FEATURE_STRIPINGV2
        - RBD_FEATURE_OBJECT_MAP
        - RBD_FEATURE_FAST_DIFF
#        - RBD_FEATURE_DEEP_FLATTEN
transforms:
  - name: zstd
    module: zstd
    configuration:
      level: 4
  - name: aes_256_gcm
    module: aes_256_gcm
    configuration:
      kdfSalt: '********************************************'
      kdfIterations: 1000
      password: '********************************'
```

Regards
David Herselman
