### ISSUE TITLE
(non-critcal) issue with restore from s3 storage being aborted with a FileNotFoundError - probably because of temporary network connectivity problem

### ISSUE THREAD

**Issue by wech71** [elemental-lf/benji#127]
**Describe the bug**

I'm not sure if it really qualifies as a bug, or an inconvenience, but it did struck me hard yesterday, because I could not complete the restore test which would have been very bad in case of a real emergency restore.

Yesterday I experienced a slight problem when trying to restore a pretty large (700 GB) backup from an off-site s3 backup, which failed after 4 hours at 81,6% because a metadata block was reported to not be found.

Of course I panicked because I thought it to be the same problem as #119, but today I checked the s3 storage and the file which reported to be missing is there:

aws s3 ls *********/blocks/85/c3 --recursive --endpoint-url https://s3.******************.com/ | grep 000000000000196c-000000000002063b
2021-09-01 08:46:25     689987 blocks/85/c3/000000000000196c-000000000002063b
2021-09-01 08:46:26        496 blocks/85/c3/000000000000196c-000000000002063b.meta

Maybe there was a temporary failure in the network connectivity which failed the read from the s3 storage

Today I tried again and this time the same restore attempt succeeded 😅 

```
    INFO: Restored 159399/160082 blocks (99.6%)
    INFO: Restored 160082/160082 blocks (100.0%)
    INFO: Successfully restored version vm-101-disk-0-dhu5lf in 03h 43m 01s with 53.6MiB/s.
```

**To Reproduce**

```
configurationVersion: '1'

logFile: /var/log/offsite-benji.log
#blockSize: 4194304
#hashFunction: BLAKE2b,digest_bits=256
processName: benji-offsite
disallowRemoveWhenYounger: 60
databaseEngine: postgresql://benji-prod-backups:D6fBV!#PZb1u@10.211.29.226:5432/benji-offsite-prod-backups
defaultStorage: s3-offsite

storages:
   - name: s3-offsite
     module: s3
     configuration:
       activeTransforms:
         - compress_zstd
         - encrypt_aes_256_gcm_1000
       awsAccessKeyId: **************************
       awsSecretAccessKey: ****************************************************
       bucketName: ****************
       endpointUrl: https://s3.**************************.com/
       connectTimeout: 300.0
       maxAttempts: 100
       readTimeout: 300.0

transforms:
   - name: compress_zstd
     module: zstd
     configuration:
       level: 3

   - name: encrypt_aes_256_gcm_1000
     module: aes_256_gcm
     configuration:
       kdfSalt: **************************
       kdfIterations: 1000
       password: **************************

ios:
   - name: file
     module: file

   - name: rbd
     module: rbd
     configuration:
       cephConfigFile: /etc/ceph/ceph.conf

```

```
benji -c /tmp/offsite-restore restore --database-less  vm-101-disk-0-dhu5lf file://_restored/pg1 -f
```

last lines output:
```
    INFO: Restored 128961/160082 blocks (80.6%)
    INFO: Restored 129762/160082 blocks (81.1%)
    INFO: Restored 130563/160082 blocks (81.6%)
   ERROR: Storage backend read failed: Object metadata or data of block 132666 (UID 196c-2063b) not found.
 WARNING: Job executor "Storage-Read" is being shutdown with 29055 outstanding jobs, cancelling them.
   ERROR: InvalidBlockException: Object metadata or data of block 132666 (UID 196c-2063b) not found.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/benji/storage/base.py", line 245, in _read
    metadata_json = self._read_object(metadata_key)
  File "/usr/local/lib/python3.9/dist-packages/benji/storage/s3.py", line 103, in _read_object
    raise FileNotFoundError('Key {} not found.'.format(key)) from None
FileNotFoundError: Key blocks/85/c3/000000000000196c-000000000002063b.meta not found.
```

**Expected behavior**

Like "Restoring Invalid Versions" I would have assumed to at least allow to retry and/or skip the missing block, instead of just aborting the restore process.

**Platform and versions (please complete the following information):**

 - Linux distribution name and version
Debian GNU/Linux 11 (bullseye)

```
uname -a
Linux workve4 5.11.22-4-pve #1 SMP PVE 5.11.22-8 (Fri, 27 Aug 2021 11:51:34 +0200) x86_64 GNU/Linux
```

```
benji version-info
    INFO: Benji version: 0.15.0.
    INFO: Configuration version: 1.0.0, supported >=1,<2.
    INFO: Metadata version: 3.0.0, supported >=1,<4.
    INFO: Object metadata version: 2.0.0, supported >=1,<3.


/usr/bin/python3 -V
Python 3.9.2


 pip list
Package                  Version
------------------------ ---------
alembic                  1.6.5
argcomplete              1.12.3
attrs                    20.3.0
bcrypt                   3.1.7
beautifulsoup4           4.9.3
benji                    0.15.0
boto3                    1.13.14
botocore                 1.20.0
cachetools               4.2.1
ceph                     1.0.0
ceph-volume              1.0.0
cephfs                   2.0.0
Cerberus                 1.3.4
certifi                  2020.6.20
chardet                  4.0.0
CherryPy                 8.9.1
colorama                 0.4.4
crit                     0.0.1
cryptography             3.3.2
cycler                   0.10.0
dacite                   1.6.0
dateparser               0.7.6
decorator                4.4.2
diskcache                5.2.1
distro                   1.5.0
fail2ban                 0.11.2
fasteners                0.14.1
google-api-python-client 1.7.11
google-auth              1.5.1
google-auth-httplib2     0.0.4
greenlet                 1.1.0
html5lib                 1.1
httplib2                 0.18.1
idna                     2.10
importlib-metadata       1.6.0
iniconfig                0.0.0
iotop                    0.6
jmespath                 0.10.0
joblib                   0.17.0
kiwisolver               1.3.1
logutils                 0.3.3
lxml                     4.6.3
Mako                     1.1.3
MarkupSafe               1.1.1
matplotlib               3.3.4
monotonic                1.5
more-itertools           4.2.0
nose                     1.3.7
numpy                    1.19.5
oauth2client             4.1.2
olefile                  0.46
packaging                20.9
Paste                    3.5.0
PasteDeploy              2.1.1
PasteScript              2.0.2
pcs                      0.10.8
pecan                    1.3.3
pexpect                  4.8.0
Pillow                   8.1.2
pip                      21.1.3
pluggy                   0.13.0
prettytable              0.7.2
protobuf                 3.12.4
psutil                   5.8.0
psycopg2-binary          2.9.1
py                       1.10.0
pyasn1                   0.4.8
pyasn1-modules           0.2.1
pycryptodome             3.10.1
pycurl                   7.43.0.6
Pygments                 2.7.1
pyinotify                0.9.6
PyJWT                    1.7.1
pyOpenSSL                20.0.1
pyparsing                2.4.7
PySimpleSOAP             1.16.2
pytest                   6.0.2
python-apt               2.2.1
python-dateutil          2.8.1
python-debian            0.1.39
python-debianbts         3.1.0
python-editor            1.0.4
pytz                     2021.1
PyYAML                   5.3.1
rados                    2.0.0
rbd                      2.0.0
regex                    2021.7.6
reportbug                7.10.3
repoze.lru               0.7
requests                 2.25.1
rgw                      2.0.0
Routes                   2.5.1
rsa                      4.0
ruamel.yaml              0.15.100
s3transfer               0.3.4
scikit-learn             0.23.2
scipy                    1.6.0
semantic-version         2.8.5
setproctitle             1.2.2
setuptools               52.0.0
simplegeneric            0.8.1
simplejson               3.17.2
six                      1.16.0
sortedcontainers         2.4.0
soupsieve                2.2.1
sparsebitfield           0.2.3
SQLAlchemy               1.4.22
structlog                21.1.0
suds-community           0.8.4
systemd-python           234
Tempita                  0.5.2
toml                     0.10.1
tornado                  6.1
tzlocal                  2.1
uritemplate              3.0.1
urllib3                  1.26.5
waitress                 1.4.4
webencodings             0.5.1
WebOb                    1.8.6
WebTest                  2.0.35
Werkzeug                 1.0.1
wheel                    0.36.2
zipp                     1.0.0
zstandard                0.15.2

```
