### ISSUE TITLE
Unable to restore backup

### ISSUE THREAD

**Issue by Gert-P** [elemental-lf/benji#133]
Hi

I urgently need to restore a backup of a ceph rdb image on proxmox. I have lost a pool and had to recreate it and I am now restoring all the images that was on that pool from a backup, however one image does not want to restore all the way, it goes fine till around 30% and then it just stops and displays "Killed"

I tried an earlier version of the same image with the same results. This is very urgent that I restore that backup. Please help
![benji Capture](https://user-images.githubusercontent.com/54531468/141793027-50838f2f-c48f-43ca-be51-4cae9fcfc7c3.JPG)
.

**Comment by Gert-P** [comment]
I have enabled DEBUG mode and now I get this:

![benji Capture](https://user-images.githubusercontent.com/54531468/141865578-797d3b80-48db-4fcf-a0f1-827003069996.JPG)

**Comment by elemental-lf** [comment]
I'm very sorry that my response took to long and I'd assume that you already found a solution or gave up on this. The logging by Benji doesn't reveal anything that might help to narrow this down. I'd suspect that the process might be killed by the kernel because of on out-of-memory condition. I'd be interested in the outcome of this so if you have the time please let me know. Thanks.

**Comment by Gert-P** [comment]
Hi

 
Yes, I unfortunately ran out of time with upset clients and had to redo the web and mail server from scratch and restore the websites and email addresses one by one, that took me a few weeks.  This now make me less confident trusting Benji. I kept the “faulty” backup for a while just to try and find out what could have gone wrong, but eventually deleted it.  I doubt that it could be a memory issue as the server had 128GB of ram and all the other vm’s restored without any problems. It was just this one that didn’t want to restore. I also tried all the versions of the vm I had available and all gave the same problem.

 
One other thing I might note is that the problematic backup was only 100GB in size and some of the other working ones were up to 2TB in size.

**Comment by Gert-P** [comment]
I just tried to restore the same VM from a new backup and ran into the same problem. I checked dmesg and as you suspected it was killed due to "Out of memory", not sure why cause I have shut down all the VMs on that node and as mentioned previously the server have 128GB of ram.

![Capture](https://user-images.githubusercontent.com/54531468/154139772-317bee35-6734-4453-9acc-6c6af0e817cc.JPG)

I was monitoring the RAM usage while the restore was running and it got higher and higher and reached 100% when the restore reached 9%, then it was killed and immediately after the ram usage dropped again back to normal.

![Capture](https://user-images.githubusercontent.com/54531468/154144523-e847e300-6047-4fa5-8206-59a9a440f009.JPG)

![Capture2](https://user-images.githubusercontent.com/54531468/154144556-26a074d6-1acb-45c7-8a92-9b6be95d80c9.JPG)

**Comment by elemental-lf** [comment]
I'm very sorry for the big inconveniences this has caused  you and appreciate that you're still willing to work on a solution with me.
I've just done a test restore of a 60GB volume which contains a production database and memory usage of Benji stayed stable over the whole restore run at about 500MB:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                 
    518 root      20   0 2473924 480432  30156 R 142.0  0.2   2:51.91 benji [Restoring version <redacted> to rbd:rbd/csi-vol-7ef85515-949f-11ec-b812-de350e70c1d2 (98.7%)]                                                             
````
I tried running Benji with a memory profiler (https://github.com/pythonspeed/filprofiler) but after some initial problems with the easy install script wrapper that Benji uses all I got from the tool was a segmentation fault. https://pypi.org/project/memory-profiler/ at least provided some output. Maybe using memory-profiler would be a good starting point for further investigation but there are other memory profilers out there. I suspect that the  multi-threadedness of Benji might make this process more difficult. It might also be difficult to get the collected output if the process is killed by the kernel OOM killer, so some code changes would be needed to generate the report before that happens. Maybe it would suffice to get some statistics of the objects on the heap to point us into the right direction (see https://github.com/zhuyifei1999/guppy3/ for example).

Unfortunately I don't have the time to work on this at the moment in my spare time and as shown I can't reproduce it for my main use case and customer. I will advise my boss to contact you. Maybe we can work something out, so that I can provide paid support to you.

**Comment by Gert-P** [comment]
Thank you for the reply, The image I am trying to restore now is around 150GB and I am restoring to RBD. I understand that you don't have time to work on it now. I am looking forward to your boss contacting me and I will be very happy if you can then provide me with paid support.

**Comment by elemental-lf** [comment]
Thank you for your understanding. I'm feeling bad because I actually do want to help but I can't do this in my spare time at the moment. In the mean time can you provide the information from the bug template (https://github.com/elemental-lf/benji/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). I'm mainly interested in your Benji version and configuration as well as your Ceph version and the kind of storage you're using for the backups.

**Comment by Gert-P** [comment]
I have an external device formatted ext4 I use for the backup, the backup is an additional mount point of a LXC container.

Benji Version:
```
    INFO: Benji version: 0.15.0.
    INFO: Configuration version: 1.0.0, supported >=1,<2.
    INFO: Metadata version: 3.0.0, supported >=1,<4.
    INFO: Object metadata version: 2.0.0, supported >=1,<3.
```

Proxmox Version 7.1.7
ceph version 16.2.6 (1a6b9a05546f335eeeddb460fdc89caadf80ac7a) pacific (stable)
Python 3.9.2

pip list
```
Package          Version
---------------- --------
alembic          1.6.5
argcomplete      1.12.3
benji            0.15.0
Cerberus         1.3.4
colorama         0.4.4
dateparser       0.7.6
diskcache        5.2.1
greenlet         1.1.1
Mako             1.1.4
MarkupSafe       2.0.1
pip              20.3.4
pkg-resources    0.0.0
prettytable      0.7.2
psycopg2-binary  2.9.1
pycryptodome     3.10.1
pyparsing        2.4.7
python-dateutil  2.8.2
python-editor    1.0.4
pytz             2021.1
rados            2.0.0
rbd              2.0.0
regex            2021.8.3
ruamel.yaml      0.15.100
semantic-version 2.8.5
setproctitle     1.2.2
setuptools       44.1.1
six              1.16.0
sortedcontainers 2.4.0
sparsebitfield   0.2.3
SQLAlchemy       1.4.22
structlog        21.1.0
tzlocal          2.1
zstandard        0.15.2
```

benji.yaml
```
configurationVersion: '1'
logFile: /var/log/benji.log
databaseEngine: sqlite:////mnt/backup/benji/benji.sqlite
blockSize: 4194304
processName: benji
disallowRemoveWhenYounger: 0
defaultStorage: usb
transforms:
  - name: compression
    module: zstd
    configuration:
      level: 3
#      dictDataFile:
storages:
  - name: usb
    storageId: 1
    module: file
    configuration:
      path: /mnt/backup/benji-data/
      activeTransforms:
        - compression
          # - name: b2
          #   storageId: 2
          #   module: b2
          #   configuration:
          #     accountId: f164bb96cda5
          #     applicationKey: 0029fcd28d1b84d2702985e43e4fcdb945a88cc0e2
          #     bucketName: hugetest
          #     writeObjectAttempts: 2
          #     uploadAttempts: 5
          #     bandwidthRead: 0
          #     bandwidthWrite: 0
          #     simultaneousWrites: 20
          #     simultaneousReads: 20
ios:
  - name: rbd
    module: rbdaio
    configuration:
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
        - RBD_FEATURE_LAYERING
        - RBD_FEATURE_EXCLUSIVE_LOCK
        - RBD_FEATURE_STRIPINGV2
      simultaneousReads: 6
  - name: file
    module: file
```


Command: benji restore -f --sparse vm-104-disk-3.h-jtlbgd rbd:ceph-hdd/vm-105-disk-0
