### ISSUE TITLE
Configuration for module benji.config is invalid after upgrade

### ISSUE THREAD

**Issue by damiandabrowski5** [elemental-lf/benji#20]
Hello,

After upgrading docker image to the latest version(based on centos) I can't run benji. I've found that config file syntax has changed so I've edited my config basing on documentation.

Unfortunately I'm still getting error:

```
# benji ls
Configuration validation errors:
  configuration.databaseEngine: required field
  configuration.io: unknown field
  configuration.ios: required field
  configuration.metadataEngine: unknown field
  configuration.storage: unknown field
  configuration.storages: required field
Uncaught exception
Traceback (most recent call last):
  File "/benji/bin/benji", line 11, in <module>
    load_entry_point('benji===unknown', 'console_scripts', 'benji')()
  File "/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 812, in main
    config = Config()
  File "/benji/lib64/python3.6/site-packages/benji/config.py", line 171, in __init__
    self._config = ConfigDict(self.validate(module=__name__, config=config))
  File "/benji/lib64/python3.6/site-packages/benji/config.py", line 127, in validate
    raise ConfigurationError('Configuration for module {} is invalid.'.format(module))
benji.exception.ConfigurationError: Configuration for module benji.config is invalid.
```

My config(i think it's fine):

```
configurationVersion: '1'

logFile: /var/log/benji/benji.log
blockSize: 4194304
#hashFunction: BLAKE2b,digest_bits=256
processName: benji
disallowRemoveWhenYounger: 6

metadataEngine: postgresql://postgres:***@postgres/benji
defaultStorage: b2

storage:
  file:
    path: /var/lib/benji/data

  b2:
     accountId: ***
     applicationKey: ***
     bucketName: ceph-backup
     writeObjectAttempts: 2
     uploadAttempts: 5

  simultaneousWrites: 10
  simultaneousReads: 10
  bandwidthRead: 0
  bandwidthWrite: 0

nbd:
  cacheDirectory: /tmp

io:
  file:
    simultaneousReads: 20

  rbd:
    cephConfigFile: /etc/ceph/ceph.conf
    simultaneousReads: 10
    simultaneousWrites: 10
    newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
      #-RBD_FEATURE_OBJECT_MAP
      #-RBD_FEATURE_FAST_DIFF
      #-RBD_FEATURE_DEEP_FLATTEN
    clientIdentifier: admin

```

error also occurs in default config copied from docs:
```
configurationVersion: '1'
dataBackend:
  type: file
  file:
    path: /tmp
metadataBackend:
  engine: sqlite:///tmp/benji.sqlite
```

**Comment by elemental-lf** [comment]
@Scooty5, oh, please be careful! You probably did miss this new text in the README:
> The current master branch is not compatible with the old master branch of 10/05/2018 and earlier and there is no migration path. The last commit supporting the old data structures is available under the tag master-20181005 if you need it. I'm sorry for any inconveniences this may cause but please also remember that Benji is still in its infancy.

Not only has the configuration structure changed as you have noticed but the data format has changed as well. So you either have to stay on the version tagged with `master-20181005 ` or you'll have to restart your backups from scratch. I think that we're reaching calmer waters now but as more users start to test and use Benji some (design) problems will probably be uncovered and will need addressing. It will be some time until Benji matures and can be fully trusted with your data. Just last week @olifre  uncovered a problem during testing which led to a database schema change. Benji will migrate your old database for you in this case but you hopefully get my point.
If you're still willing to test Benji then I'd like to add  that documentation for the new configuration file format is lacking at the moment. Currently the best place to look for guidance and examples is https://github.com/elemental-lf/benji/blob/4fa517c3576e32fd8e05bdb5ca55359d395f0928/src/benji/tests/test_smoketest.py. Starting around line 221.

**Comment by damiandabrowski5** [comment]
Thanks for the response, 

I understand that benji is currently at development stage but can I ask how long it could take to reach the stage where documentation will be up to date? I'd be very happy to test benji and help in development but It's highly uncomfortable now, when documentation gives incorrect informations :/

**Comment by elemental-lf** [comment]
@Scooty5, I've just push a documentation update for the configuration file which should hopefully shed some light on it. Please see http://benji-backup.me/configuration.html. Feel free to open a new issue if something is still unclear, I'll close this one.

**Comment by damiandabrowski5** [comment]
Hello,

Unfortunately https://benji-backup.me/quickstart.html is still outdated, simple 7 line configuration doesn't work.

Additionally, in new 'configuration' section there aren't any example configuration which I can base on. Example configuration was available before and it was extremely helpful!

**Comment by damiandabrowski5** [comment]
Hello,

I've created example configuration for ceph and backblaze


```
configurationVersion: '1'
logFile: /var/log/benji/benji.log
blockSize: 4194304
processName: benji
disallowRemoveWhenYounger: 6
databaseEngine: postgresql://postgres:***@postgres/benji
defaultStorage: b2

ios:
- name: rbd
  module: rbd
  configuration:
    cephConfigFile: /etc/ceph/ceph.conf
    clientIdentifier: admin
    newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
    simultaneousReads: 20

storages:
- name: b2
  storageId: 1
  module: b2
  configuration:
    accountId: ***
    applicationKey: ***
    bucketName: ceph-backup
    writeObjectAttempts: 2
    uploadAttempts: 5
    bandwidthRead: 0
    bandwidthWrite: 0
    simultaneousWrites: 20
    simultaneousReads: 20

```
