### ISSUE TITLE
Helm chart missing configmaps for ceph-etc and ceph-client-admin-keyring

### ISSUE THREAD

**Issue by ArcticSnowman** [elemental-lf/benji#44]
The helm chart deployment has 

```
        # Ceph volumes start
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-client-admin-keyring
          secret:
            secretName: ceph-client-admin-keyring
        # Ceph end
```

But there is no configmap template to create those...
