### ISSUE TITLE
ERROR: ModuleNotFoundError: No module named 'rados'

### ISSUE THREAD

**Issue by Gert-P** [elemental-lf/benji#50]
When trying to do `benji database-init` I get the following error:

```
INFO: $ /usr/local/benji/bin/benji database-init
ERROR: ModuleNotFoundError: No module named 'rados'
```

My configuration looks like this:

```
configurationVersion: '1'
logFile: /var/log/benji.log
databaseEngine: sqlite:////backup/benji.sqlite
blockSize: 4194304
processName: benji
disallowRemoveWhenYounger: 6
defaultStorage: local
storages:
  - name: local
    storageId: 1
    module: file
    configuration:
      path: /backup/
  - name: b2
    storageId: 2
    module: b2
    configuration:
      accountId: {blablabla}
      applicationKey: {blablabla}
      bucketName: hugetest
      writeObjectAttempts: 2
      uploadAttempts: 5
      bandwidthRead: 0
      bandwidthWrite: 0
      simultaneousWrites: 20
      simultaneousReads: 20
ios:
  - name: rbd
    module: rbd
    configuration:
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
        - RBD_FEATURE_LAYERING
        - RBD_FEATURE_EXCLUSIVE_LOCK
        - RBD_FEATURE_STRIPINGV2
      simultaneousReads: 20
  - name: file
    module: file
```
