### ISSUE TITLE
Can't make backblaze backups

### ISSUE THREAD

**Issue by redtex** [elemental-lf/benji#58]
Hello.
I've created a simple setup which is follows:
```
configurationVersion: '1'                                                                                                                                                                                                                                                                                      
databaseEngine: postgresql://benji:***@192.168.107.151/benji
defaultStorage: cloud-backups
storages:
  - name: cloud-backups
    storageId: 1
    module: b2
    configuration:
      accountId: 0cc**
      applicationKey: 003**
      bucketName: cephbackup
ios:
  - name: rbd
    module: rbdaio
    configuration:
      simultaneousReads: 5
      simultaneousWrites: 5 
```
When i try to make backup, i've get following error message:
ERROR: InvalidAuthToken: Invalid authorization token. Server said:  (bad_auth_token)

The accountId (Master application Key) and applicationKey are correct.
What I am doing wrong ?
