### ISSUE TITLE
Using Encryption

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#60]
Testing out the encryption of benji.

Here is what I have in my config (replaced master key with xxx).    

transforms:
  - name: encryption
    module: aes_256_gcm
    configuration:
      masterKey: xxxxxxxxxxxxx

Did a backup, then commented out the above in the benji.yaml. 

Kicked off a restore and it seems to be restoring the data, shouldn't it fail if encryption is enabled and it doesn't have the masterKey?

**Comment by elemental-lf** [comment]
Did you add the new transform to the list of `activeTransforms` for the storage? Something similar to this from `test_smoketest.py`:
```yaml
            storages:
            - name: s2
              module: s3
              configuration:
                [...]
                activeTransforms:
                  - zstd
                  - k1
            transforms:
            - name: zstd
              module: zstd
              configuration:
                level: 1
            - name: k1
              module: aes_256_gcm
              configuration:
                kdfSalt: BBiZ+lIVSefMCdE4eOPX211n/04KY1M4c2SM/9XHUcA=
                kdfIterations: 20000
                password: "this is a very secret password"
```
Transforms listed in `activeTransforms` are applied in order when writing objects to the storage. So encryption transforms should normally come last. On read the transforms are applied in the reverse order of the list  recorded in the object's metadata, regardless of the currently configured `activeTransforms`. This makes it possible to activate compression or encryption even when there are existing backups and will facilitate key rollover in the future.
If you use `masterKey` instead of the listed directives please ensure that it has a high entropy.
